### PR TITLE
Add Passport passReqToCallback option

### PR DESCRIPTION
**Pull request by oladon**
Thanks for the library!

This PR adds the `passReqToCallback` option to the Passport strategy.

Let me know if there's anything you'd like done differently.

### CODE REVIEW

**Comment by panva** [comment]
- lts/4 should still be passing, please avoid unsupported syntax
- tests are missing (cov)

Can you change the PR?

**Comment by oladon** [comment]
I'll see what I can do.

Is the spread operator is the unsupported syntax you're referencing?

**Comment by panva** [comment]
This looks great, thank you @oladon

**Comment by panva** [comment]
just now realized it's a part of params, i might refactor a bit to have it a part of options directly.

**Pull request merged**
